### ISSUE TITLE
3 or 4 days?  6 or 7 Modules?

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#109]
Description of issue
* According to this repository, specifically the "Trainer Guide.md" file, there is an agenda that outlines this course as a 3-day course with 7 modules.
* However, the MCT Download says there are 4 days, not 3, and there are 6 modules, not 7.

And the MCT download says that Day 1-2 cover the Modules, with Day 3 being a "Bithub business case lab, please note that the lab has its own instructor manual"...   and then Day 4 is "The Applied Workshop should take up this entire fourth day."

So I can't figure out what I'm supposed to teach.........

**Comment by julians1966** [comment]
The Trainer Guide.md file needs to be updated to match the course change to 6 modules as laid out in the Trainer Prep Guide on the Learning Download Center.

The Trainer Guide.md file also need to be updated for the addition of the applied workshop on Day 4

**Comment by tylerfarmer1** [comment]
If Day #4 is where the student pick 1 of the 3 scenarios, what are we supposed to teach on Day #3?

The project called "Company 311" is what we already do during Day #1 and #2.   So I still don't know what to do on Day #3.

Tyler Farmer
***@***.******@***.***>
602-326-1042

**Comment by julians1966** [comment]
As it says in https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/blob/master/Trainer%20Guide.md 

Day 3 is a full day of hands-on-labs where students will be building a company 311 solutions. At the beginning of the day, you will present the students with the solution and talk about some of the key elements in the lab. Since students will be working on labs all day, you should check back with them periodically to keep them engaged. After each lab is completed, check back, and talk about some of the discussion points related to that lab as well as introduce the tasks and expectations for the next lab.

You are not teaching at this point juts guiding them through the labs

The majority of https://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker/blob/master/Trainer%20Guide.md is what you say and when you say it.
