### ISSUE TITLE
The formulas in lab 03.1 are showing multiple errors.

### ISSUE THREAD

**Issue by kini04** [MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker#150]
# Module: 02
#### Step: 8,9,10

Description of issue
The formula given for the Reserve button is erroneous. 
Step 8 formula: If(BrowseGallery1.Selected.Availability = [@Availability].Available, DisplayMode.Edit, DisplayMode.Disabled)

Step 9 formula: Patch(Gadgets, BrowseGallery1.Selected, {Availability: [@Availability].Reserved, 'Reserved by': CurrentUser})

Step 10 Formula: If(EditForm1.Mode = FormMode.View, true, false)

The instructions in the lab are also not aligned with the interface.

**Comment by kini04** [comment]
The error in
Step 8 is Name isn't valid. Availability not recognized.
Step 9 is function Patch has invalid formulas

**Comment by ephiax20** [comment]
Pretty sure this is the same as #152    This has occurred because the **Availability** Choice column has not been synced with a Global choice of the same name. The UI does not allow you to do this if you create the column while the table hasn't been fully created yet.   We are reviewing & fixing the instructions to be clearer about this and moving the creation of Availability Choice to the next task.
